name: Build and Publish .NET Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    env:
      DOTNET_ROOT: "${{ github.workspace }}\\publish-output"  # Output directory

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show current directory
        run: echo %cd%

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.317'

      - name: Restore dependencies
        run: dotnet restore ./BlogApi/BlogApi.csproj

      - name: Build the project
        run: dotnet build ./BlogApi/BlogApi.csproj --configuration Release

      - name: Show directory contents
        run: dir

      - name: Publish the app