name: Build and deploy ASP.Net Core app to Azure Web App - BlogApi

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Publish the app
        run: dotnet publish ./BlogApi/BlogApi.csproj -c Release -o "${{ github.workspace }}/publish"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: "${{ github.workspace }}/publish"

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: "${{ github.workspace }}/publish"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: 3f649468-79f9-4081-ac82-14128bcf6841
          tenant-id: 4e253ebb-6f2d-47fe-ba79-3e191596cff0
          subscription-id: 93a5a51f-2b5f-4cf5-a887-01d39fc1423a

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BookStore'
          slot-name: 'Production'
          package: "${{ github.workspace }}/publish"